### ISSUE TITLE
Logout socket hang up

### ISSUE THREAD

**Issue by laravieira** [carlrygart/portainer-stack-deploy#28]
Getting this error while logging out, everything works, the stack is deployed correctly, just breaks the action:
![Image](https://github.com/user-attachments/assets/5d15fe30-c4f7-40d5-b585-7b54347988fa)
```
      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{ secrets.PORTAINER_HOST }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'super-secret-stack-name'
          stack-definition: 'docker-compose.prod.yml' 
          image: ${{ env.DOCKER_IMAGE_URI }}:${{ env.IMAGE_TAG }}
          prune-stack: true
          pull-image: true
```
Am I missing any configs?
